### ISSUE TITLE
ERROR: Wrong parameters for register device

### ISSUE THREAD

**Issue by mohamed-hmd** [xueminghao/appstoreconnectapi#1]
I tried to register a device using this command

asca --tools register-device --udid fcd7ld989ca879060ee9b644gnd98dea33dabb8 -n hmd -a profile-download -n pro-01

**Comment by mhxue** [comment]
To register a device only, you can simply call a device related post api by following command:

`asca --api device --method post --udid [udid] --name [device_name]`

**Comment by mhxue** [comment]
Issue's been closed, if there exists more questions please reopen it for free.

**Comment by mohamed-hmd** [comment]
I want a way to add a new certificate
