### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by mohamed-hmd** [xueminghao/appstoreconnectapi#2]
hot to add new api token and remove old

**Comment by mohamed-hmd** [comment]
I found the solution Thank you

But When this command was used

asca --tools register-device -a profile-download -n embedded

I get error 

ERROR: Wrong parameters for register device

**Comment by mhxue** [comment]
Sorry, there's a typo in the readme, fixed now~~

**Comment by mohamed-hmd** [comment]
This command can be used to add a new device 

asca --tool register-device --udid [udid] --name [device-name] --profile-names [profile-names]

Without the need for this command

asca --api device --method post --udid [udid] --name [device-name]

**Comment by mhxue** [comment]
The upper one can also update the specified provisioning files

**Comment by mohamed-hmd** [comment]
Last question
If I have a lot of devices to add, how ...?

**Comment by mhxue** [comment]
Just call the command in an iteration~~
By the way, where are you from,man?

**Comment by mohamed-hmd** [comment]
how please (Just call the command in an iteration~~) send me command
I'm from Algeria

**Comment by mhxue** [comment]
You can call it from a shell script.I think you should lean some shell knowledge. But don't worry, only a little shell knowledge is enough.Just google "shell iteration" to do that

**Comment by mohamed-hmd** [comment]
I have not found a solution, can you help me 😪

**Comment by mohamed-hmd** [comment]
help me and I well pay
